name: Run .NET Tests
description: Ejecuta pruebas con dotnet test, reporte JUnit y subida de artefactos
inputs:
  configuration:
    description: Build configuration (Debug/Release)
    required: false
    default: Release

runs:
  using: composite
  steps:
    - name: 💾 Restaurar cache de bin/obj
      uses: actions/cache@v4
      with:
        path: |
          **/bin/
          **/obj/
        key: build-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          build-${{ runner.os }}-

    - name: 🧪 Ejecutar pruebas con reporte JUnit
      shell: bash
      run: |
        dotnet test --no-build --configuration ${{ inputs.configuration }} \
          --logger:"junit;LogFileName=test-results.xml"

    - name: 📤 Subir resultado de pruebas
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test-results.xml'
